export const readingCoverMap: Record<string, string> = {
  'The Marines of Montford Point: America\'s First Black Marines': '/reading/covers/the-marines-of-montford-point-americas-first-black-marines.webp',
  'Echo in Ramadi: The Firsthand Story of US Marines in Iraq\'s Deadliest City': '/reading/covers/echo-in-ramadi-the-firsthand-story-of-us-marines-in-iraqs-deadliest-city.webp',
  "Neptune's Inferno: The U.S. Navy at Guadalcanal": '/reading/covers/neptunes-inferno-the-u-s-navy-at-guadalcanal.webp',
  "Risk: A User's Guide": '/reading/covers/risk-a-users-guide.webp',
  "The Defence of Duffer's Drift": '/reading/covers/the-defence-of-duffers-drift.webp',
  "Ender's Game": '/reading/covers/enders-game.webp',
  "Speed Kills: Leveraging John Boyd's OODA Loop to Build Organizations That Win": '/reading/covers/speed-kills-leveraging-john-boyds-ooda-loop-to-build-organizations-that-win.webp',
  "The Generals' War: The Inside Story of the Conflict in the Gulf": '/reading/covers/the-generals-war-the-inside-story-of-the-conflict-in-the-gulf.webp',
  "The Long Game: China's Grand Strategy to Displace American Order": '/reading/covers/the-long-game-chinas-grand-strategy-to-displace-american-order.webp',
  'How the Few Became the Proud: Crafting the Marine Corps Mystique, 1874-1918': '/reading/covers/how-the-few-became-the-proud-crafting-the-marine-corps-mystique-1874-1918.webp',
  "Lejeune: A Marine's Life, 1867-1942": '/reading/covers/lejeune-a-marines-life-1867-1942.webp',
  'First to Fight: An Inside View of the U.S. Marine Corps': '/reading/covers/first-to-fight-an-inside-view-of-the-u-s-marine-corps.webp',
  'Always Faithful: 250 Years of Remarkable Stories from the Collections of the National Museum of the Marine Corps': '/reading/covers/always-faithful-250-years-of-remarkable-stories-from-the-collections-of-the-national-museum-of-the-marine-corps.webp',
  'Semper Fidelis: 250 Years of U.S. Marine Corps Honor, Courage, and Commitment': '/reading/covers/semper-fidelis-250-years-of-u-s-marine-corps-honor-courage-and-commitment.webp',
  'With the Old Breed: At Peleliu and Okinawa': '/reading/covers/with-the-old-breed-at-peleliu-and-okinawa.webp',
  'Delivering Destruction: American Firepower and Amphibious Assault from Tarawa to Iwo Jima': '/reading/covers/delivering-destruction-american-firepower-and-amphibious-assault-from-tarawa-to-iwo-jima.webp',
  'This Kind of War: The Classic Korean War History, 50th Anniversary Edition': '/reading/covers/this-kind-of-war-the-classic-korean-war-history-50th-anniversary-edition.webp',
  'Code Talker: The First and Only Memoir by One of the Original Navajo Code Talkers of WWII': '/reading/covers/code-talker-the-first-and-only-memoir-by-one-of-the-original-navajo-code-talkers-of-wwii.webp',
  'Corps Competency?: III Marine Amphibious Force Headquarters in Vietnam': '/reading/covers/corps-competency-iii-marine-amphibious-force-headquarters-in-vietnam.webp',
  'Targeted: Beirut: The 1983 Marine Barracks Bombing and the Untold Story of the War on Terror': '/reading/covers/targeted-beirut-the-1983-marine-barracks-bombing-and-the-untold-story-of-the-war-on-terror.webp',
  'The American War in Afghanistan: A History': '/reading/covers/the-american-war-in-afghanistan-a-history.webp',
  'On Contested Shores: The Evolving Role of Amphibious Operations in the History of Warfare (Vols. I & II)': '/reading/covers/on-contested-shores-the-evolving-role-of-amphibious-operations-in-the-history-of-warfare-vols-i-and-ii.webp',
  'Learning War: The Evolution of Fighting Doctrine in the U.S. Navy, 1898-1945': '/reading/covers/learning-war-the-evolution-of-fighting-doctrine-in-the-u-s-navy-1898-1945.webp',
  'A Game of Birds and Wolves: The Ingenious Young Women Whose Secret Board Game Helped Win World War II': '/reading/covers/a-game-of-birds-and-wolves-the-ingenious-young-women-whose-secret-board-game-helped-win-world-war-ii.webp',
  'Playing War: Wargaming and U.S. Navy Preparations for World War II': '/reading/covers/playing-war-wargaming-and-u-s-navy-preparations-for-world-war-ii.webp',
  'A New Conception of War: John Boyd, the U.S. Marines, and Maneuver Warfare': '/reading/covers/a-new-conception-of-war-john-boyd-the-u-s-marines-and-maneuver-warfare.webp',
  'Where Good Ideas Come From: The Natural History of Innovation': '/reading/covers/where-good-ideas-come-from-the-natural-history-of-innovation.webp',
  'The Origins of Victory: How Disruptive Military Innovation Determines the Fates of Great Powers': '/reading/covers/the-origins-of-victory-how-disruptive-military-innovation-determines-the-fates-of-great-powers.webp',
  'Evolution on Demand: The Changing Roles of the U.S. Marine Corps in Twenty-first Century Conflicts and Beyond': '/reading/covers/evolution-on-demand-the-changing-roles-of-the-u-s-marine-corps-in-twenty-first-century-conflicts-and-beyond.webp',
  '7 Seconds to Die: A Military Analysis of the Second Nagorno-Karabakh War and the Future of Warfighting': '/reading/covers/7-seconds-to-die-a-military-analysis-of-the-second-nagorno-karabakh-war-and-the-future-of-warfighting.webp',
  'Next War: Reimagining How We Fight': '/reading/covers/next-war-reimagining-how-we-fight.webp',
  'The Fourth Industrial Revolution': '/reading/covers/the-fourth-industrial-revolution.webp',
  'Soft-Wired: How the New Science of Brain Plasticity Can Change Your Life': '/reading/covers/soft-wired-how-the-new-science-of-brain-plasticity-can-change-your-life.webp',
  'Co-Intelligence: Living and Working with AI': '/reading/covers/co-intelligence-living-and-working-with-ai.webp',
  'Generative AI for Leaders': '/reading/covers/generative-ai-for-leaders.webp',
  'The Arms of the Future: Technology and Close Combat in the 21st Century': '/reading/covers/the-arms-of-the-future-technology-and-close-combat-in-the-21st-century.webp',
  'Make Your Bed': '/reading/covers/make-your-bed.webp',
  'You Are Worth It: Building a Life Worth Fighting For': '/reading/covers/you-are-worth-it-building-a-life-worth-fighting-for.webp',
  'The White Donkey: Terminal Lance': '/reading/covers/the-white-donkey-terminal-lance.webp',
  'On Killing': '/reading/covers/on-killing.webp',
  'Wisdom of the Bullfrog': '/reading/covers/wisdom-of-the-bullfrog.webp',
  'Matterhorn: A Novel of the Vietnam War': '/reading/covers/matterhorn-a-novel-of-the-vietnam-war.webp',
  'The Yompers: With 45 Commando in the Falklands War': '/reading/covers/the-yompers-with-45-commando-in-the-falklands-war.webp',
  'Generals and Admirals, Criminals and Crooks': '/reading/covers/generals-and-admirals-criminals-and-crooks.webp',
  'Leadership Strategy and Tactics: Field Manual': '/reading/covers/leadership-strategy-and-tactics-field-manual.webp',
  'The Greatest U.S. Marine Corps Stories Ever Told': '/reading/covers/the-greatest-u-s-marine-corps-stories-ever-told.webp',
  'Call Sign Chaos: Learning to Lead': '/reading/covers/call-sign-chaos-learning-to-lead.webp',
  'Nimitz at War': '/reading/covers/nimitz-at-war.webp',
  'Five Generations at Work: How We Win Together, For Good': '/reading/covers/five-generations-at-work-how-we-win-together-for-good.webp',
  'Essentialism: The Disciplined Pursuit of Less': '/reading/covers/essentialism-the-disciplined-pursuit-of-less.webp',
  'The Closing of the American Mind': '/reading/covers/the-closing-of-the-american-mind.webp',
  'Legacy: 15 Lessons in Leadership': '/reading/covers/legacy-15-lessons-in-leadership.webp',
  'The Infinite Game': '/reading/covers/the-infinite-game.webp',
  'Turn the Ship Around!: A True Story of Turning Followers into Leaders': '/reading/covers/turn-the-ship-around-a-true-story-of-turning-followers-into-leaders.webp',
  'On Grand Strategy': '/reading/covers/on-grand-strategy.webp',
  'The New Makers of Modern Strategy: From the Ancient World to the Digital Age': '/reading/covers/the-new-makers-of-modern-strategy-from-the-ancient-world-to-the-digital-age.webp',
  'Ground Combat: Puncturing the Myths of Modern War': '/reading/covers/ground-combat-puncturing-the-myths-of-modern-war.webp',
  'Command: The Politics of Military Operations from Korea to Ukraine': '/reading/covers/command-the-politics-of-military-operations-from-korea-to-ukraine.webp',
  'The Russian Way of Deterrence: Strategic Culture, Coercion & War': '/reading/covers/the-russian-way-of-deterrence-strategic-culture-coercion-war.webp',
  'Fleet Tactics and Naval Operations, 3rd ed.': '/reading/covers/fleet-tactics-and-naval-operations-3rd-ed.webp',
  'Chinese Amphibious Warfare: Prospects for a Cross-Straits Invasion': '/reading/covers/chinese-amphibious-warfare-prospects-for-a-cross-straits-invasion.webp',
  'Constitution of the United States of America': '/reading/covers/constitution-of-the-united-states-of-america.webp',
  'Warfighting (MCDP 1)': '/reading/covers/warfighting-mcdp-1.webp',
  'Competing (MCDP 1-4)': '/reading/covers/competing-mcdp-1-4.webp',
  'Intelligence (MCDP 2)': '/reading/covers/intelligence-mcdp-2.webp',
  'Expeditionary Operations (MCDP 3)': '/reading/covers/expeditionary-operations-mcdp-3.webp',
  'Logistics (MCDP 4)': '/reading/covers/logistics-mcdp-4.webp',
  'Learning (MCDP 7)': '/reading/covers/learning-mcdp-7.webp',
  'Leading Marines (MCWP 6-11)': '/reading/covers/leading-marines-mcwp-6-11.webp',
  'Sustaining the Transformation (MCRP 6-11D)': '/reading/covers/sustaining-the-transformation-mcrp-6-11d.webp',
};
