import { readFileSync, writeFileSync } from 'fs';
import { geoPath, geoMercator } from 'd3-geo';
import { feature } from 'topojson-client';

// Use unprojected data + per-state Mercator fit → north-up, no Albers tilt
const topoJson = JSON.parse(
  readFileSync(new URL('../node_modules/us-atlas/states-10m.json', import.meta.url), 'utf8')
);

const stateNameToAbbr = {
  Alabama: 'AL', Alaska: 'AK', Arizona: 'AZ', Arkansas: 'AR', California: 'CA',
  Colorado: 'CO', Connecticut: 'CT', Delaware: 'DE', 'District of Columbia': 'DC',
  Florida: 'FL', Georgia: 'GA', Hawaii: 'HI', Idaho: 'ID', Illinois: 'IL',
  Indiana: 'IN', Iowa: 'IA', Kansas: 'KS', Kentucky: 'KY', Louisiana: 'LA',
  Maine: 'ME', Maryland: 'MD', Massachusetts: 'MA', Michigan: 'MI', Minnesota: 'MN',
  Mississippi: 'MS', Missouri: 'MO', Montana: 'MT', Nebraska: 'NE', Nevada: 'NV',
  'New Hampshire': 'NH', 'New Jersey': 'NJ', 'New Mexico': 'NM', 'New York': 'NY',
  'North Carolina': 'NC', 'North Dakota': 'ND', Ohio: 'OH', Oklahoma: 'OK',
  Oregon: 'OR', Pennsylvania: 'PA', 'Rhode Island': 'RI', 'South Carolina': 'SC',
  'South Dakota': 'SD', Tennessee: 'TN', Texas: 'TX', Utah: 'UT', Vermont: 'VT',
  Virginia: 'VA', Washington: 'WA', 'West Virginia': 'WV', Wisconsin: 'WI',
  Wyoming: 'WY',
};

const states = feature(topoJson, topoJson.objects.states).features;
const PADDING = 8;

const shapes = {};

for (const f of states) {
  const name = f.properties.name;
  const abbr = stateNameToAbbr[name];
  if (!abbr) continue;

  // Use a rough Mercator fit to get the correct aspect ratio for this state
  const roughProj = geoMercator().fitSize([500, 500], f);
  const [[x0, y0], [x1, y1]] = geoPath().projection(roughProj).bounds(f);
  const w = x1 - x0;
  const h = y1 - y0;

  const vbW = Math.round(w + PADDING * 2);
  const vbH = Math.round(h + PADDING * 2);

  // Fit Mercator to final viewBox with padding — north-up, no projection tilt
  const fittedProj = geoMercator()
    .fitExtent([[PADDING, PADDING], [vbW - PADDING, vbH - PADDING]], f);

  const fittedPath = geoPath().projection(fittedProj);
  const d = fittedPath(f);
  const [translateX, translateY] = fittedProj.translate();

  shapes[abbr] = {
    viewBox: `0 0 ${vbW} ${vbH}`,
    d,
    projection: {
      scale: fittedProj.scale(),
      translate: [translateX, translateY],
    },
  };
}

// Sort by key
const sorted = Object.fromEntries(Object.entries(shapes).sort(([a], [b]) => a.localeCompare(b)));

const lines = Object.entries(sorted).map(([abbr, { viewBox, d, projection }]) => {
  // Escape backticks in path string (shouldn't be any, but just in case)
  const safeD = d.replace(/`/g, '\\`');
  return `  ${abbr}: {\n    viewBox: '${viewBox}',\n    d: \`${safeD}\`,\n    projection: { scale: ${projection.scale}, translate: [${projection.translate[0]}, ${projection.translate[1]}] },\n  },`;
});

const output = `// Auto-generated by scripts/generateStateShapes.mjs — do not edit manually
// Source: us-atlas states-10m.json with per-state Mercator projection metadata
export const STATE_SHAPES: Record<string, { viewBox: string; d: string; projection: { scale: number; translate: [number, number] } }> = {
${lines.join('\n')}
};

export function stateCodeFromMha(mha: string): string | null {
  const match = mha.match(/^([A-Z]{2})\\d/);
  return match ? match[1] : null;
}
`;

writeFileSync(new URL('../src/app/features/pay/stateShapes.ts', import.meta.url), output, 'utf8');
console.log(`Generated ${Object.keys(sorted).length} state shapes.`);
